name: Build and Verify

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  build-and-verify:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify PR
        id: verify_pr
        continue-on-error: true
        run: |
          echo "Hi"
          echo "github.event.number" ${{ github.event.number }}

      - name: Save PR number
        if: always()
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: pr
          path: pr/
